### PR TITLE
Update sites.json

### PR DESCRIPTION
**Pull request by brisray**
Add brisray to Loop Webring

### CODE REVIEW

**Comment by Graycot** [comment]
Welcome to the loop ring!

**Comment by brisray** [comment]
Hi,

 

There appears to be something wrong with what’s happening with the links in the Loop Webring code. What is happening is that instead of picking a new site up, the browser address bar goes to for example https://loop.graycot.dev/webring.html?action=next and then just stops. No action is being performed.

 

The code is on https://brisray.com/utils/webrings.htm and the same thing happens to the code on https://docs.graycot.dev/s/MFowZsw_F

 

My page needs a little tidying up. I joined several webrings the same day and I plan to style some of the links given.

 

Ray

**Comment by Graycot** [comment]
Hey Ray, thanks for the heads up! There was an extra comma in` sites.json` that broke the JSON formatting and caused `webring.js` to fail while reading the member list. I have corrected the issue and am planning to add a fallback to handle JSON formatting errors in the future.

I found the page on your website describing the history of Web Rings at https://brisray.com/web/webrings.htm. This page is the best collection of Web Ring information I have read, and it is incredibly through. It's a great resource!
  
I have something that might be of interest to you. A while back I wrote the [Oring](https://docs.graycot.dev/s/_t1vKY7M-#) template, which is the FOSS code that Loop Ring runs. My goal was to create a selfhostable webring that did not require any server-side computing. The purpose of this was to allow people to easily run their own webrings  by uploading the files to a free static file host such as Neocities or to deploy from a git repo to Netlify. Additionally, it would have the added benefit of a longer lifespan than other webrings due to not requiring home server upkeep or VPS subscription costs.

It has been disappointing to see the majority of Webrings that I have joined over time disappear or break, but at the same time, I am enjoying the rebirth of webring culture and the small-web movement. I'm optimistic that there is more to the future of Web Rings on the current modern web.

**Comment by brisray** [comment]
Those pesky commas and brackets in JSON and JS!

 

I joined some other “new” webrings recently and it really is a pity that they seem so underused. Worse still, a lot of the members do not seem to realize that if a visitor can’t find them on their site then they break them. 

 

I’m glad people like yourself are bringing them back. In the olden days they were needed because search engines were not that great. Now they are needed because small personal sites can’t get a look-in on them, they’re buried on page 87 of the search results.

 

It is kinda fun looking at what people are doing on places like Neocities, it reminds me of the days of Lycos Tripod and the others.

 

Ray

**Comment by brisray** [comment]
Hi,

I've just been to [https://loop.graycot.dev/member-list.html](https://loop.graycot.dev/member-list.html) and

**Pull request merged**
