### PR TITLE
My Application to Loop Ring

### PR DESCRIPTION
**Pull request by Mcbuzzerr**

### CODE REVIEW

**Comment by Graycot** [comment]
Hey McBuzzerr! I like your website a lot, finding the keystroke combination Easter egg was fun! 

Let me know once you have added  the Loop Ring widget to your site and I'll approve to commit to add your site to the ring.

Cheers and happy web-deving!

**Review by Graycot — CHANGES_REQUESTED** [review]
Hey McBuzzerr! I like your website a lot, finding the keystroke combination Easter egg was fun!

Let me know once you have added the Loop Ring widget to your site and I'll approve the PR to add your site to the ring.

Cheers and happy web-deving!

**Comment by Mcbuzzerr** [comment]
Oh my bad! I originally had the widget, but then I thought that I maybe shouldn't put it on before I was actually in the webring so I removed it.
It's now officially there again!
I plan to join multiple web rings and I want the widgets to be on different pages, with loopring being on my AboutMe page.
It's annoying when the webring widget isn't on the page that you land on when coming from another site in the ring, so if you could make sure it links to my AboutMe page that would be wonderful

**Comment by Graycot** [comment]
No worries! I feel the same way about the webring widget being on the same page that the visitor is directed onto. Welcome to the LoopRing!

**Pull request merged**
